# commit to be tagged for the new release
commit = "HEAD"

project_name = "kube-service-exposer"
github_repo = "siderolabs/kube-service-exposer"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.3.0"

[notes.metrics-bind-address]
title = "Configurable Metrics Bind Address"
description = """\
The metrics server is now disabled by default and can be enabled by setting the new `--metrics-bind-addr` flag to the desired listen address.

Previously it was always enabled on `:8080` on all interfaces.
"""
