apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-service-exposer
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-service-exposer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-service-exposer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-service-exposer
subjects:
  - kind: ServiceAccount
    name: kube-service-exposer
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-service-exposer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-service-exposer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-service-exposer
    spec:
      serviceAccountName: kube-service-exposer
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
      containers:
        - name: kube-service-exposer
          image: ghcr.io/siderolabs/kube-service-exposer:v0.2.0
          # args:
          #   - --debug=true
          #   - --pprof-bind-addr=:6060
          #   - --annotation-key=my-annotation-key/port
          #   - --bind-cidrs=172.20.0.0/24
